# hugo.toml
baseURL = 'https://lab.artkov-info.ru/'
languageCode = 'ru-ru'
title = 'Цифровой сад и мастерская'
theme = 'hugo-theme-stack'
defaultContentLanguage = 'ru'

[pagination]
pagerSize = 6

[permalinks]
post = "/:year/:month/:slug/"
page = "/:slug/"

[services.disqus]
shortname = "your-disqus-shortname" # Замени на свой реальный shortname
